In [1]:
import tensorflow as tf

# TO cheack version 

In [4]:
print("tensorflow version",tf.__version__)
print("keras version",tf.keras.__version__)

tensorflow version 2.2.0
keras version 2.3.0-tf


# GPU/CPU cheack

In [5]:
variavle = tf.Variable([3,3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
  print('CPU') 

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
CPU


In [9]:
variable = tf.Variable([3,3])
if tf.config.list_physical_devices('GPU'):
    print('GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
  print('CPU') 

CPU


In [7]:
# so here we using cpu

In [10]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3], dtype=int32)>

# Variable can be changed but constent not 
# so we create variable as well as constent 

In [13]:
ineoron = tf.constant(42) 
print(ineoron)

tf.Tensor(42, shape=(), dtype=int32)


In [17]:
ineoron.dtype,ineoron.shape,ineoron.numpy()

(tf.int32, TensorShape([]), 42)

In [18]:
ineoron.numpy()

42

In [21]:
ineouron1 = tf.constant(1,dtype='float64') 
print(ineouron1)

tf.Tensor(1.0, shape=(), dtype=float64)


In [24]:
print(ineouron1.numpy())
print(ineouron1.shape)
print(ineouron1.dtype)

1.0
()
<dtype: 'float64'>


In [26]:
ineouron2 = tf.constant([[4,5],[9,5]]) 

In [31]:
print("Dimension  is :  ", ineouron2.ndim)
print("value  is  :  ", ineouron2.numpy())
print(type(ineouron2))

Dimension  is :   2
value  is  :   [[4 5]
 [9 5]]
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [32]:
print(type(variable))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


# in python we directly create variable but in tensornflow we can't   so we use Variable() 

In [33]:
#  constant tensor
ineouron_x = tf.constant([[4,5],[5,6]])
ineouron_x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [5, 6]], dtype=int32)>

In [36]:
print(ineouron_x.ndim)
print(ineouron_x.shape)
print(ineouron_x.numpy())

2
(2, 2)
[[4 5]
 [5 6]]


# commonly method to genrate ones and zeros constant

In [37]:
print(tf.ones((2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [44]:
zero =  tf.zeros((2,3)) 
print(zero.shape)
print(zero.ndim)
print(zero.numpy())
print(type(zero)) 

(2, 3)
2
[[0. 0. 0.]
 [0. 0. 0.]]
<class 'tensorflow.python.framework.ops.EagerTensor'>


# EagerTensor means constant

In [46]:
cons1 = tf.constant([1,2,3])
cons2 = tf.constant([4,5,6])
print(cons1)
print(cons2)
print(type(cons1))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [52]:
result = tf.add(cons1,cons2) 
print(result)
print(type(result))   # EagerTensor means constant 
print(result.numpy())

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
[5 7 9]


In [53]:
cons1 = tf.constant([[1,2,3],[4,5,6]])
cons2 = tf.constant([[1,2,3],[4,5,6]]) 
result = tf.add(cons1,cons2)
print(result)

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


# Random constant

In [54]:
nor =  tf.random.normal(shape=(2,3),mean=0.0,stddev=1.0)
print(nor)

tf.Tensor(
[[-0.02249253  0.5637521  -0.58584976]
 [-0.8418973  -1.1369345   0.0436615 ]], shape=(2, 3), dtype=float32)


In [65]:
sum = 0
l = []
for i in nor.numpy():
   for value in i:
       l.append(value)

In [71]:
import numpy as np 
ar = np.array(l)
print(ar.mean())
print(ar.std())

-0.32996008
0.5790247


In [73]:
uni = tf.random.uniform((2,3),minval=0,maxval=10,dtype='float64')
print(uni) 
print(type(uni)) 

tf.Tensor(
[[2.89864807 6.0057023  0.31824391]
 [9.07214495 6.91008108 5.46275611]], shape=(2, 3), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'>


# Declaring  Variable

In [83]:
var0 = 24   # python variable
var1 = tf.Variable(24)   # rank 0
var2 = tf.Variable([[[1,2,3],[4,5,6],[7,8,9]]]) 

In [81]:
print(var0)
print(var1)
print(type(var1))
print(var1.numpy())


24
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=24>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
24


In [85]:
var0,var1,var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=24>,
 <tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=int32)>)

In [87]:
val = tf.Variable(89,dtype='float64') 
print(val.numpy())  

89.0


# to reassign variable use var.assign() 

In [92]:
var_reassign = tf.Variable(98.0) 
var_reassign = 100    
print(var_reassign)

# so thos is not assignment 

100


In [95]:
var_reassign = tf.Variable(98.0) 
var_reassign.assign(100)
print(var_reassign)
print(var_reassign.numpy())  # so  this is assignment 

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=100.0>
100.0


In [99]:
initial_value = tf.random.normal((2,3)) 
a = tf.Variable(initial_value) 
print(type(a))
a.numpy()

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


array([[-1.146671  , -1.421821  , -0.21343577],
       [-0.29796645, -1.4594502 ,  1.360646  ]], dtype=float32)

# Assign and add 

In [100]:
new_value = tf.random.normal((2,3))

In [101]:
a.assign(new_value) 
a 

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[-1.483324  , -0.31522927,  1.2857589 ],
       [ 1.0885727 ,  1.0435888 , -0.12965886]], dtype=float32)>

In [102]:
added_value = tf.random.normal((2,3))
a.assign_add(added_value)
print("Addtion result is",a) 

Addtion result is <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[-1.9478459 , -1.1061342 ,  0.56697786],
       [ 1.0000547 ,  1.1177332 ,  0.4267751 ]], dtype=float32)>


In [103]:
tensor = tf.Variable([ [ [10.0,11.0,12.0],[13.0,14.0,15.0],[16.0,17.0,18.0] ] ]) 
print(tensor)

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]], dtype=float32)>


In [105]:
print(tensor.shape)

(1, 3, 3)


In [117]:
tensor = tf.Variable([ [ [1,2,3] ,[4,5,6] ]  , [[1,2,3],[4,5,6] ] ])      
print(tensor)
print(tensor.shape)
print(tensor.numpy())


<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>
(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Reshape

In [125]:
tensor.value

<bound method BaseResourceVariable.value of <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>>

In [126]:
tensor1 = tf.reshape(tensor,shape=(6,2)) 
tensor1

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [128]:
tensor2 = tf.reshape(tensor,shape=(1,12)) 
tensor2.numpy()

array([[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]], dtype=int32)

In [133]:
tensor3 = tf.reshape(tensor,shape=(4,-1))    # here only -1 works    other - number is not work
tensor3.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [135]:
tensor4 = tf.reshape(tensor,shape=(1,-12))   # - 123456 number is not works
tensor4.numpy()

InvalidArgumentError: ignored

# Tensor Rank

#### The rank of tensor is define as the number of dimension , wich is the number of indices that are requried  to specify any perticuller element of that tensor

In [137]:
print(tensor.numpy() )
print(tf.rank(tensor))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
tf.Tensor(3, shape=(), dtype=int32)


# specify an element of a tensor

In [142]:
tensor3 = tensor[1,0,2]   # 1 slice   0 row  2 column
tensor3.numpy() 

3

In [144]:
tensor.numpy()

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)

In [145]:
type(tensor.numpy())

numpy.ndarray

# Tensorflow mathematics operation 

In [146]:
a = tf.random.normal((2,2)) 
b = tf.random.normal((2,2))  

In [148]:
print(a.numpy())
print(b.numpy()) 

[[-1.284799   -0.9058731 ]
 [ 0.33304456  0.4131534 ]]
[[ 1.1032935   0.23584598]
 [-0.29743668  0.79361916]]


In [149]:
c = a+b
print(c.numpy()) 

[[-0.18150544 -0.67002714]
 [ 0.03560787  1.2067726 ]]


In [150]:
-1.284799   +  1.1032935

-0.1815055000000001

In [151]:
d = tf.square(c)
print(d)

tf.Tensor(
[[3.2944225e-02 4.4893637e-01]
 [1.2679207e-03 1.4563000e+00]], shape=(2, 2), dtype=float32)


In [153]:
e  = tf.exp(c)
print(e)

tf.Tensor(
[[0.8340137  0.51169467]
 [1.0362494  3.342679  ]], shape=(2, 2), dtype=float32)


# Perfrom element wise premitve  operaton

In [156]:
tensor10  = tf.Variable([10,20])  
tensor11 = tf.Variable([[10,20]]) 
print((tensor10*tensor11).numpy()) 

[[100 400]]


# Broadcasting in a tensor

In [157]:
tensor12 = tensor10*2
print(tensor12)

tf.Tensor([20 40], shape=(2,), dtype=int32)


# Transpose matrix miltiplection 

In [162]:
matrix_u = tf.constant([[1,2,3]]) 
matrix_v = tf.constant([[4,5,6]]) 


In [163]:
tf.matmul(matrix_u,tf.transpose(matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[32]], dtype=int32)>

In [164]:
14+18

32

# Casting a tensor in some other datatype

In [166]:
tf.cast(matrix_u,dtype='float64').numpy()

array([[1., 2., 3.]])

# Casting with tranction

In [169]:
tf.cast([4.9],dtype=tf.int32).numpy()   # gives lower value

array([4], dtype=int32)

# Ragged array

In [170]:
ragged = tf.ragged.constant([[1,2,3],[] ,[1,2] ,[1]]) 
ragged

<tf.RaggedTensor [[1, 2, 3], [], [1, 2], [1]]>

In [172]:
tf.constant([[1,2],[]])

ValueError: ignored

# Squared diffrnce of tensors

In [174]:
varx = [4,5,6,1,2]
vary = 8 
varz = tf.math.squared_difference(varx,vary)   # Returns (x - y)(x - y) element-wise
varz.numpy()

array([16,  9,  4, 49, 36], dtype=int32)

# calculating the mean

In [175]:
numbers = tf.constant([[1,2,3],[4,5,6]]) 
numbers


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [177]:
tf.reduce_mean(input_tensor=numbers).numpy()

3

In [181]:
tf.reduce_max([12,3]).numpy()

12

In [183]:
tf.reduce_min([12,3,45,6,44]).numpy()

3

In [185]:
tf.reduce_sum([12,2]).numpy()

14

In [189]:
tf.reduce_prod([4,5,3]).numpy()

60

# setting the seed

In [192]:
tf.random.set_seed(10) 
num1 = tf.random.normal((2,3),mean=0.0,stddev=1.0)
num2 = tf.random.normal((2,3),mean=0.0,stddev=1.0)
print(num1)
print(num2) 

tf.Tensor(
[[-0.8757808   0.3356369  -0.35219625]
 [-0.3031456  -0.03882965  0.96529824]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.4831794  -0.97205937 -1.8948057 ]
 [-0.5673938  -1.3298559  -0.4534591 ]], shape=(2, 3), dtype=float32)


In [205]:
tf.random.set_seed(10)
dice1 = tf.Variable(tf.random.uniform([4,1] ,minval=0,maxval=10)) 
dice2 = tf.Variable(tf.random.uniform([4,1] ,minval=0,maxval=10)) 
dice3 = dice1+dice2
tf.concat([dice1,dice2,dice3] ,axis=0) 

<tf.Tensor: shape=(12, 1), dtype=float32, numpy=
array([[ 6.4415097],
       [ 8.082472 ],
       [ 8.976547 ],
       [ 6.3689017],
       [ 5.5478153],
       [ 4.2658195],
       [ 1.4140713],
       [ 7.0369396],
       [11.989325 ],
       [12.348291 ],
       [10.390618 ],
       [13.405842 ]], dtype=float32)>

In [206]:
tf.concat([dice1,dice2,dice3] ,axis=1) 


<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 6.4415097,  5.5478153, 11.989325 ],
       [ 8.082472 ,  4.2658195, 12.348291 ],
       [ 8.976547 ,  1.4140713, 10.390618 ],
       [ 6.3689017,  7.0369396, 13.405842 ]], dtype=float32)>

In [207]:
dice1,dice2,dice3


(<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
 array([[6.4415097],
        [8.082472 ],
        [8.976547 ],
        [6.3689017]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
 array([[5.5478153],
        [4.2658195],
        [1.4140713],
        [7.0369396]], dtype=float32)>,
 <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
 array([[11.989325],
        [12.348291],
        [10.390618],
        [13.405842]], dtype=float32)>)

In [208]:
t = tf.constant([1,2,3,4,56])

In [210]:
loc = tf.argmax(t)
t[loc].numpy() 

56

In [211]:
loc = tf.argmin(t)
t[loc].numpy() 

1

# cheackpoint

In [215]:
variable1 = tf.Variable([[1,2,3],[4,5,6]]) 
cheakpoint = tf.train.Checkpoint(var = variable1)
savepath = cheakpoint.save('./vars')
variable1.assign([[0,0,0],[0,0,0]])
variable1
cheakpoint.restore(savepath)
print(variable1) 

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


# Function

In [219]:
def f1(x,y):
  return tf.reduce_mean(input_tensor=tf.multiply(x ** 3,6) + y ** 3)
func = tf.function(f1) 

In [220]:
x = tf.constant([3.,-4.])
y = tf.constant([1.,4.]) 
func(x,y)

<tf.Tensor: shape=(), dtype=float32, numpy=-78.5>

In [221]:
func(4,5)

<tf.Tensor: shape=(), dtype=int32, numpy=509>

In [222]:
a = tf.random.normal((2,2))
b = tf.random.normal((2,2))
with tf.GradientTape() as tape:
  print(tape.watch(a)) 
  c = tf.sqrt(tf.square(a) + tf.square(b)) 
  print(c)
  dc_da = tape.gradient(c,a) 
  print(dc_da)

None
tf.Tensor(
[[0.9308666 1.6030818]
 [0.432032  0.8771298]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.33435947 -0.96524227]
 [ 0.8265694  -0.94369376]], shape=(2, 2), dtype=float32)
